# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/EECS_443_project/C8VHDL/Chip8_cur_BAK/chip8/mem_test/mem_test/mem_test.cache/wt [current_project]
set_property parent.project_path H:/EECS_443_project/C8VHDL/Chip8_cur_BAK/chip8/mem_test/mem_test/mem_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/EECS_443_project/C8VHDL/Chip8_cur_BAK/chip8/mem_test/mem_test/mem_test.srcs/sources_1/new/mem_mod.vhd
  H:/EECS_443_project/C8VHDL/Chip8_cur_BAK/chip8/mem_test/mem_test/mem_test.srcs/sources_1/new/mem_controller.vhd
  H:/EECS_443_project/C8VHDL/Chip8_cur_BAK/chip8/mem_test/mem_test/mem_test.srcs/sources_1/new/mem_test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mem_test -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mem_test.dcp

catch { report_utilization -file mem_test_utilization_synth.rpt -pb mem_test_utilization_synth.pb }
