# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.cache/wt [current_project]
set_property parent.project_path H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.srcs/sources_1/new/core.vhd
  H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.srcs/sources_1/new/cntr_test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.srcs/constrs_1/new/cntr_test_const.xdc
set_property used_in_implementation false [get_files H:/EECS_443_project/C8VHDL/Chip8/chip8/cntr_test/cntr_test/cntr_test.srcs/constrs_1/new/cntr_test_const.xdc]


synth_design -top cntr_test -part xc7a100tcsg324-1


write_checkpoint -force -noxdef cntr_test.dcp

catch { report_utilization -file cntr_test_utilization_synth.rpt -pb cntr_test_utilization_synth.pb }
