## Clock signal
#Bank = 35, Pin name = IO_L12P_T1_MRCC_35,					Sch name = CLK100MHZ
set_property PACKAGE_PIN E3 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
##set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

## switches
## control
set_property PACKAGE_PIN U9 [get_ports {keyPad[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[0]}]
set_property PACKAGE_PIN U8 [get_ports {keyPad[1]}]	
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[1]}]
set_property PACKAGE_PIN R7 [get_ports {keyPad[2]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[2]}]
set_property PACKAGE_PIN R6 [get_ports {keyPad[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[3]}]
set_property PACKAGE_PIN R5 [get_ports {keyPad[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[4]}]
set_property PACKAGE_PIN V7 [get_ports {keyPad[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[5]}]
set_property PACKAGE_PIN V6 [get_ports {keyPad[6]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[6]}]
set_property PACKAGE_PIN V5 [get_ports {keyPad[7]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[7]}]
set_property PACKAGE_PIN U4 [get_ports {keyPad[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[8]}]
set_property PACKAGE_PIN V2 [get_ports {keyPad[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[9]}]
set_property PACKAGE_PIN U2 [get_ports {keyPad[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[10]}]
set_property PACKAGE_PIN T3 [get_ports {reset}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN T1 [get_ports {gameSelect[0]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[0]}]
set_property PACKAGE_PIN R3 [get_ports {gameSelect[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[1]}]
set_property PACKAGE_PIN P3 [get_ports {gameSelect[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[2]}]
set_property PACKAGE_PIN P4 [get_ports {gameSelect[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[3]}]

## Push buttons
set_property PACKAGE_PIN F15 [get_ports {keyPad[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[11]}]
set_property PACKAGE_PIN T16 [get_ports {keyPad[12]}]	
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[12]}]
set_property PACKAGE_PIN E16 [get_ports {keyPad[13]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[13]}]
set_property PACKAGE_PIN R10 [get_ports {keyPad[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[14]}]
set_property PACKAGE_PIN V10 [get_ports {keyPad[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[15]}]

## LEDs
set_property PACKAGE_PIN P2 [get_ports {err_code[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {err_code[2]}]
set_property PACKAGE_PIN R2 [get_ports {err_code[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {err_code[1]}]
set_property PACKAGE_PIN U1 [get_ports {err_code[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {err_code[0]}]
set_property PACKAGE_PIN P5 [get_ports {heart_beat}]
    set_property IOSTANDARD LVCMOS33 [get_ports {heart_beat}]
set_property PACKAGE_PIN R1 [get_ports {buzz}]
    set_property IOSTANDARD LVCMOS33 [get_ports {buzz}]
set_property PACKAGE_PIN V1 [get_ports {cpu_active}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cpu_active}]
set_property PACKAGE_PIN U3 [get_ports {mem_active}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_active}]
set_property PACKAGE_PIN V4 [get_ports {vga_active}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_active}]
set_property PACKAGE_PIN U6 [get_ports {mapped_out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[7]}]
set_property PACKAGE_PIN U7 [get_ports {mapped_out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[6]}]
set_property PACKAGE_PIN T4 [get_ports {mapped_out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[5]}]
set_property PACKAGE_PIN T5 [get_ports {mapped_out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[4]}]
set_property PACKAGE_PIN T6 [get_ports {mapped_out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[3]}]
set_property PACKAGE_PIN R8 [get_ports {mapped_out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[2]}]
set_property PACKAGE_PIN V9 [get_ports {mapped_out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[1]}]
set_property PACKAGE_PIN T8 [get_ports {mapped_out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mapped_out[0]}]
    
##VGA Connector
set_property PACKAGE_PIN A3 [get_ports {VGA_RED_O[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED_O[0]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_RED_O[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED_O[1]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_RED_O[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED_O[2]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_RED_O[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED_O[3]}]
    
set_property PACKAGE_PIN C6 [get_ports {VGA_GREEN_O[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN_O[0]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_GREEN_O[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN_O[1]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_GREEN_O[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN_O[2]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_GREEN_O[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN_O[3]}]

set_property PACKAGE_PIN B7 [get_ports {VGA_BLUE_O[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE_O[0]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_BLUE_O[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE_O[1]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_BLUE_O[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE_O[2]}]
set_property PACKAGE_PIN D8 [get_ports {VGA_BLUE_O[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE_O[3]}]

set_property PACKAGE_PIN B11 [get_ports {VGA_HS_O}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_HS_O}]
set_property PACKAGE_PIN B12 [get_ports {VGA_VS_O}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VGA_VS_O}]
    
set_property PACKAGE_PIN A11 [get_ports {audioAMP}]
    set_property IOSTANDARD LVCMOS33 [get_ports {audioAMP}]
    
set_property PACKAGE_PIN D12 [get_ports {audioEn}]
    set_property IOSTANDARD LVCMOS33 [get_ports {audioEn}]
