## Clock signal
#Bank = 35, Pin name = IO_L12P_T1_MRCC_35,					Sch name = CLK100MHZ

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

## switches
## control
set_property PACKAGE_PIN U9 [get_ports {clk}]
	set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN U8 [get_ports {keyPad[1]}]	
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[1]}]
set_property PACKAGE_PIN R7 [get_ports {keyPad[2]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[2]}]
set_property PACKAGE_PIN R6 [get_ports {keyPad[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[3]}]
set_property PACKAGE_PIN R5 [get_ports {keyPad[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[4]}]
set_property PACKAGE_PIN V7 [get_ports {keyPad[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[5]}]
set_property PACKAGE_PIN V6 [get_ports {keyPad[6]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[6]}]
set_property PACKAGE_PIN V5 [get_ports {keyPad[7]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[7]}]
set_property PACKAGE_PIN U4 [get_ports {keyPad[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[8]}]
set_property PACKAGE_PIN V2 [get_ports {keyPad[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[9]}]
set_property PACKAGE_PIN U2 [get_ports {keyPad[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[10]}]
set_property PACKAGE_PIN T3 [get_ports {reset}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN T1 [get_ports {gameSelect[0]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[0]}]
set_property PACKAGE_PIN R3 [get_ports {gameSelect[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[1]}]
set_property PACKAGE_PIN P3 [get_ports {gameSelect[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[2]}]
set_property PACKAGE_PIN P4 [get_ports {gameSelect[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[3]}]

## Push buttons
set_property PACKAGE_PIN F15 [get_ports {keyPad[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[11]}]
set_property PACKAGE_PIN T16 [get_ports {keyPad[12]}]	
	set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[12]}]
set_property PACKAGE_PIN E16 [get_ports {keyPad[13]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[13]}]
set_property PACKAGE_PIN R10 [get_ports {keyPad[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[14]}]
set_property PACKAGE_PIN V10 [get_ports {keyPad[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[0]}]

## LEDs
set_property PACKAGE_PIN P2 [get_ports {debug_read_data[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[7]}]
set_property PACKAGE_PIN R2 [get_ports {debug_read_data[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[6]}]
set_property PACKAGE_PIN U1 [get_ports {debug_read_data[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[5]}]
set_property PACKAGE_PIN P5 [get_ports {debug_read_data[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[4]}]
set_property PACKAGE_PIN R1 [get_ports {debug_read_data[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[3]}]
set_property PACKAGE_PIN V1 [get_ports {debug_read_data[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[2]}]
set_property PACKAGE_PIN U3 [get_ports {debug_read_data[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[1]}]
set_property PACKAGE_PIN V4 [get_ports {debug_read_data[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {debug_read_data[0]}]
set_property PACKAGE_PIN U6 [get_ports {mem_state[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[7]}]
set_property PACKAGE_PIN U7 [get_ports {mem_state[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[6]}]
set_property PACKAGE_PIN T4 [get_ports {mem_state[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[5]}]
set_property PACKAGE_PIN T5 [get_ports {mem_state[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[4]}]
set_property PACKAGE_PIN T6 [get_ports {mem_state[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[3]}]
set_property PACKAGE_PIN R8 [get_ports {mem_state[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[2]}]
set_property PACKAGE_PIN V9 [get_ports {mem_state[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[1]}]
set_property PACKAGE_PIN T8 [get_ports {mem_state[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_state[0]}]