set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

## switches
## control
set_property PACKAGE_PIN U9 [get_ports {memRead[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {memRead[0]}]
set_property PACKAGE_PIN U8 [get_ports {memRead[1]}]	
	set_property IOSTANDARD LVCMOS33 [get_ports {memRead[1]}]
set_property PACKAGE_PIN R7 [get_ports {memRead[2]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[2]}]
set_property PACKAGE_PIN R6 [get_ports {memRead[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[3]}]
set_property PACKAGE_PIN R5 [get_ports {memRead[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[4]}]
set_property PACKAGE_PIN V7 [get_ports {memRead[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[5]}]
set_property PACKAGE_PIN V6 [get_ports {memRead[6]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[6]}]
set_property PACKAGE_PIN V5 [get_ports {memRead[7]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {memRead[7]}]
##set_property PACKAGE_PIN U4 [get_ports {keyPad[8]}]
##    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[8]}]
##set_property PACKAGE_PIN V2 [get_ports {keyPad[9]}]
##    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[9]}]
##set_property PACKAGE_PIN U2 [get_ports {keyPad[10]}]
##    set_property IOSTANDARD LVCMOS33 [get_ports {keyPad[10]}]
##set_property PACKAGE_PIN T3 [get_ports {reset}]    
##    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
##set_property PACKAGE_PIN T1 [get_ports {gameSelect[0]}]    
##    set_property IOSTANDARD LVCMOS33 [get_ports {gameSelect[0]}]
set_property PACKAGE_PIN R3 [get_ports {mem_done}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_done}]
set_property PACKAGE_PIN P3 [get_ports {reset}]
    set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN P4 [get_ports {clk}]
    set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

## LEDs
--set_property PACKAGE_PIN P2 [get_ports {}]
--    set_property IOSTANDARD LVCMOS33 [get_ports {}]
set_property PACKAGE_PIN R2 [get_ports {mem_hold}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_hold}]
set_property PACKAGE_PIN U1 [get_ports {mem_write}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_write}]
set_property PACKAGE_PIN P5 [get_ports {mem_valid}]
    set_property IOSTANDARD LVCMOS33 [get_ports {mem_valid}]
set_property PACKAGE_PIN R1 [get_ports {memAddress[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[11]}]
set_property PACKAGE_PIN V1 [get_ports {memAddress[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[10]}]
set_property PACKAGE_PIN U3 [get_ports {memAddress[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[9]}]
set_property PACKAGE_PIN V4 [get_ports {memAddress[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[8]}]
set_property PACKAGE_PIN U6 [get_ports {memAddress[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[7]}]
set_property PACKAGE_PIN U7 [get_ports {memAddress[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[6]}]
set_property PACKAGE_PIN T4 [get_ports {memAddress[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[5]}]
set_property PACKAGE_PIN T5 [get_ports {memAddress[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[4]}]
set_property PACKAGE_PIN T6 [get_ports {memAddress[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[3]}]
set_property PACKAGE_PIN R8 [get_ports {memAddress[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[2]}]
set_property PACKAGE_PIN V9 [get_ports {memAddress[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[1]}]
set_property PACKAGE_PIN T8 [get_ports {memAddress[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {memAddress[0]}]